# 网关配置文件
port: 8090
timeout: 15s
rate_limit: 100

# 服务配置
services:
  student-api:
    url: "http://localhost:3060"
    prefix: "/api/v1"
    weight: 1
    health_check: "/health"

# 负载均衡配置
load_balancer:
  strategy: "round_robin"  # round_robin, random, weighted
  health_check: true
  check_interval: 30s
  check_timeout: 5s

# CORS配置
cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  allow_credentials: true
  max_age: 86400

# 安全配置
security:
  enable_https: false
  cert_file: ""
  key_file: ""
  
# 日志配置
logging:
  level: "info"
  format: "json"
  enable_access_log: true